import typing

class Agent:
    def __new__(cls,name:str, system_prompt:str, config:LLMConfig): ...
    def run(self, user_input,stream_callback = ...,prune = ...) -> str:
        ...

    def register_tool(self, func) -> None:
        ...


class LLMConfig:
    def __new__(cls,model,api_key,provider = ...,base_url = ...): ...
    ...

